name: DCP

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: dcp
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:  [ "5.0.1", "5.1.3", "5.5.6", "6.0.5", "6.5.2", "6.6.6", "7.0.5", "7.1.6", "7.2.3" ]
        build: [ linux ]
        include:
          - build: linux
            os: ubuntu-latest
            rust: stable

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust ${{ matrix.rust }}
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}

      - name: Rustfmt
        run: |
          cargo fmt -- --check

      - uses: Swatinem/rust-cache@v2

      - name: Test DCP
        run: |
          cargo test --release --package dcp-rs --test integration_test -- --exact --nocapture
        env:
          RUST_LOG: debug
          CB_VERSION: ${{ matrix.version }}